# Generated by Django 3.0.8 on 2020-08-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('apellido1', models.CharField(max_length=60)),
                ('apellido2', models.CharField(max_length=60)),
            ],
        ),
    ]
